backend:
  name: git-gateway
  branch: wifey
media_folder: "static/uploads"
collections:
  - name: "blog" 
    label: "Blog" 
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post-layout.njk"}
      - {label: "Tag", name: "tags", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
