on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: us-east-1

      - name: Install dependencies & build site
        run: |
          npm ci
          npm run build

      - name: Copy files to S3
        run: |
          aws s3 sync _site/ s3://${{ secrets.BUCKET_NAME }} --delete